# Generated by Django 5.0.1 on 2024-04-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_machineissue_temp_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissuereview',
            name='malfunction_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.spares'),
        ),
    ]
