# Generated by Django 5.0.1 on 2024-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machineissuereview_malfunction_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineissuereview',
            name='malfunction_part',
        ),
        migrations.AddField(
            model_name='machineissuereview',
            name='malfunction_part',
            field=models.ManyToManyField(null=True, related_name='spares', to='core.spares'),
        ),
    ]
