# Generated by Django 5.0.1 on 2024-04-27 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_machineissuereview_malfunction_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ended', models.DateTimeField(auto_now=True)),
                ('supervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('technician', models.CharField(blank=True, max_length=50, null=True)),
                ('solutionDescription', models.TextField(default='EMPTY')),
                ('remarks', models.TextField(default='EMPTY')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolved_issues', to='core.contractor')),
                ('issueReview', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.machineissuereview')),
            ],
        ),
        migrations.DeleteModel(
            name='IssueResolution',
        ),
    ]
