# Generated by Django 5.0.1 on 2024-04-29 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_machineissuereview_malfunction_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueclosing',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='issueclosing',
            name='image',
            field=models.ManyToManyField(related_name='closingImages', to='core.imagemodel'),
        ),
        migrations.AddField(
            model_name='issueclosing',
            name='machineHours',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='issueclosing',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolved_issues', to='core.contractor'),
        ),
    ]
