# Generated by Django 5.0.1 on 2024-04-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_issueclosing_duration_issueclosing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueclosing',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='issueclosing',
            name='machineHours',
            field=models.IntegerField(),
        ),
    ]
