# Generated by Django 5.0.1 on 2024-04-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_issueclosing_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueclosing',
            name='equipment_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AlterField(
            model_name='machineissuereview',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machineissue', to='core.machineissue'),
        ),
    ]
