# Generated by Django 5.0.1 on 2024-04-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_issueclosing_equipment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueclosing',
            name='equipment_status',
            field=models.CharField(max_length=10),
        ),
    ]
