# Generated by Django 5.0.1 on 2024-06-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_issueclosing_equipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineissue',
            name='temp_review_id',
        ),
        migrations.AddField(
            model_name='machineissue',
            name='error_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
