# Generated by Django 5.0.1 on 2024-06-13 11:38
from django.db import migrations, models



def set_error_department_values(apps, schema_editor):
    issue = apps.get_model('core', 'MachineIssue')

    for issue in issue.objects.all():
        if not issue.user.department:
            issue.delete()
            print(f"{issue} user has no department")
            continue
        print(issue.user.department)
        issue.error_department = issue.user.department



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_machineissue_temp_review_id_and_more'),
    ]

    operations = [
        migrations.RunPython(set_error_department_values)
    ]
