# Generated by Django 5.0.1 on 2024-06-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240614_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineissue',
            name='error_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
